language: R
cache: packages

before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'

jobs:
  include:
  - r: 3.2
  - os: osx
  - r: 3.5
  - r: devel
    script:
    - R CMD build .
    - R CMD check *tar.gz

# not working yet
# deploy:
#      provider: script
#      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
#      skip_cleanup: true
